tickers = [
    {"ticker": "NU", "discount_rate": 45},
    {"ticker": "PLTR", "discount_rate": 40, "csp_percentage_down": -0.25},
    {"ticker": "NVDA", "discount_rate": 20},
    {"ticker": "HOOD", "discount_rate": 60, "csp_percentage_down": -0.25},
    {"ticker": "GOOGL", "discount_rate": 25},
    {"ticker": "AMZN", "discount_rate": 25},
    {"ticker": "TSLA", "discount_rate": 45},
    # {"ticker": "VOO", "discount_rate": 10}, 
    {"ticker": "RKLB", "discount_rate": 45, "csp_percentage_down": -0.25},
    {"ticker": "ASTS", "discount_rate": 50, "csp_percentage_down": -0.25},
    # {"ticker": "HIMS", "discount_rate": 78, "csp_percentage_down": -0.25},
    {"ticker": "BTC-USD", "discount_rate": 49, "csp_percentage_down": -0.3},
    # {"ticker": "MSTR", "discount_rate": 30},
    {"ticker": "NEXT", "discount_rate": 63, "csp_percentage_down": -0.35},
    {"ticker": "NBIS", "discount_rate": 45, "csp_percentage_down": -0.30},
    {"ticker": "IREN", "discount_rate": 60, "csp_percentage_down": -0.30},
    # {"ticker": "ACHR", "discount_rate": 35},
    # {"ticker": "JOBY", "discount_rate": 25},
    # {"ticker": "OSCR", "discount_rate": 41},
    # {"ticker": "TEM", "discount_rate": 36.5},
    {"ticker": "VG", "discount_rate": 77, "csp_percentage_down": -0.5}
]
